name: Deploy to Server

on:
  push:
    branches:
      - debug

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --exclude 'node_modules' ./ $SERVER_USER@$SERVER_HOST:/iserra-api
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cd /iserra-api && npm install && npm run start"
        shell: bash
